keys:
  # Users
  - &users:
    - &sjcobb age1qcrgm4maymy44cws6p0qcfhrjqpra75zdwkwh9hvvvzg7vs4uudq5x4j7n
  # Hosts
  - &hosts:
    - &slaptop age1ygqez4yjlggfekj8sgtsfda4v5up3x5946u5yn8e82elrr5rvdzqt3n7z6
    - &velocity age1a4yag0568a423nf2vg8nzpp46nxxz08stl63veqz06k52husa5cqju04vl 

creation_rules:
  - path_regex: hosts/slaptop/secrets.ya?ml$
    key_groups:
    - age:
      - *slaptop
      - *sjcobb

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *slaptop
      - *velocity
      - *sjcobb
