keys:
  # Users
  - &users:
    - &sjcobb age16ph0xq7xqfe8pmcwtgpvsw4sgeeclmajx0mln28ffrh8nrly7vnqscf559
  # Hosts
  - &hosts:
    - &slaptop age1yh3xne5p2uncmhzw96zegk3zzezel5ndruf0z6qerk098ww28qvq94a4zp
    - &velocity age1a4yag0568a423nf2vg8nzpp46nxxz08stl63veqz06k52husa5cqju04vl 

creation_rules:
  - path_regex: hosts/slaptop/secrets.ya?ml$
    key_groups:
    - age:
      - *slaptop
      - *sjcobb

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *slaptop
      - *velocity
      - *sjcobb
